openapi: "3.0.0"
info:
  title: Get Vehicle
  version: 1.0.0
paths:
  /api/vehicle:
    get:
      summary: Get Vehicle
      description: Get Vehicle
      tags:
        - greeting
      parameters:
        - name: name
          in: query
          description: Name of the person to greet
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []