-- CREATE TABLE IF NOT EXISTS EMPLOYEE (
--     EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
--     FIRST_NAME VARCHAR(255) NOT NULL,
--     LAST_NAME VARCHAR(255),
--     EMAIL VARCHAR(255)
-- );

INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Bilbo', 'Baggins', 'bilbo@bagend.me');